= katori
== bo
=== 1ste
houding rechts /
aanval, uitstappen naar links (praktisch ni, ne voet is al te ver) + bo erop
wapenen + uistappen naar rechts + yokomen van rechts
zitten + opening
aanval komt + uitspringen naar links en opvangen
wapenen + yokomen van links
wapenen + yokomen van rechts, maar is schijnbeweging om dan te zitten en een slag naar de enkel te doen
ze vangen op, schuiven naar voor om je pols aan te vallen
snel springen naar rechts en bo op het wapen leggen
achteruit smijten
klaar

=== 2de
houding rechts /
aanval, uitstappen naar links (praktisch ni, ne voet is al te ver) + bo erop
zakken + mune links
wapenen + uistappen naar rechts + yokomen van rechts
zakken + tsune rechts
wapenen + shomen (recht naar het hoofd)
vangt speciaal op
steken, door de armen
achteruit smijten
klaar

=== 3de (sayuu no bo)
bo horizontaal, rechts, naar achter (voorste stuk vasthouden)
aanval komt
linkervoet naar achter en bo erop leggen in shomen-achtige slag
wapenen en yokomen links
bo naar achter smijten, zoals in't begin en wachten
aanval komt
uitspringen naar links en bo vangt de aanval op
wapenen + do van links aanvallen
opening laten
aanval komt
uitspringen, rechts naar achter en opvangen aanval met bo
wapenen + yokomen rechts aanvallen
naar achter smijten en stopceremonie naar links gericht uitvoeren
klaar

=== 4de
horizontaal vanachter vastpakken, naar tegenstander kijken
over kop, om strooien hoed eraf te doen en wachten
tegenstander doet een maki uchi
bo terug naar voor, maar op shouderhoogte houden
aanval komt
wapenen, hiki naar achter en erop leggen (juist uit de aanvalslijn, maar uiteindelijke richting moet je nog
beschermen en is dus naar de tegenstander gericht)
wapenen + yokomen rechts
tegenstander vangt te ure gasumi op, gelijk ne kabute eronder door,
en valt dan je zijkant do aan.
wegspringen en bo erop leggen, duw zijn katana naar beneden.
tegenstander gaat daardoor naar gedan no kamae.
wapenen + yokomen links
wapenen + yokomen rechts
zakken, tsune links
naar achter smijten, ceremonie naar rechts gericht uitvoeren
klaar


