== Aikibudo
tenbin nage:
* niet te ver gaan, dichtbij blijven
* steeds beide handen gebruiken (kamae houding)
* tai sabaki o-irimi volledig afwerken = je staat bekan terug recht voor de tegenstander
* op het einde, elleboog op zijn binnenarm en met de snijkant van je hand hem naar beneden brengen
* terug recht laten komen en `kablamo`
Stage info tenbin:
* Niet blokkeren. Laten komen en trekken. 
* oo-irimi niet volledig afwerken, je eindigt met je voeten parallel. Dan kan je de techniek zelf gemakkelijker uitvoeren. Er ligt wel een nadruk op het naar achter trekken, zodat zijn beweging verder blijft gaan en je daar gebruik van kunt maken.
Stage info ryote ippo dori:
* niet uit evenwicht brengen door arm te strekken naar voren! Bekken draaien en dan plaats maken en direct uitstappen. Anders lost hij en gaat hij naar een wurging.
Stage info mukae daoshi:
* Opletten met de arm die je onder controle neemt: die breng je naar beneden, maar die moet langs de buitenkant blijven. Anders zal je het wel voelen aan je ballen.
* Zie ook dat zijn schouder niet te veel gedraaid is, zodat zijn rug in een rechte kamae houding komt. Dat zorgt voor de problemen met het wringen aan de nek en dat je arm-kracht moet gebruiken.
Go-ten - 1:
* Op knieën zitten, ze pakken je rechterhand vast met hun rechterhand. Klem zetten (vingers achteruit plooien), naar boven. Arm over je hoofd brengen.
* Klem zetten hierboven, door eerst je een beetje te richten naar tegenstander (knieën iets draaien/bijschuiven naar rechts).
* Onderwegen arm breken op je hoofd.
* Arm verder schuiven en in je nek leggen, zodat een elleboog klem in de richting van je gi-lijn gezet wordt.
Go-ten - 2:
* Ze pakken je linkerarm vast, in het voorbij-gaan. Vastpakken gebeurd met de rechterarm.
* Draaien en de arm over je hoofd plaatsen, zodat hij aan de ander kan komt.
* Je bent helemaal meegedraaid, je knieën zijn nu naar rechts gericht. Dus 270 graden gedraaid.
* Omver leggen, met je rechterschouder.
Go-ten - 3:
* Ze wurgen je langs achter.
* Arm vastpakken en tegenstander naar voren smijten, met je gewicht.
* Linkervoet gaat naar buiten.
Go-ten - 4:
* Ze pakken je 2 polsen langs voor vast, met hun 2 handen.
* Kracht breken (cfr. Aiki)
* je armen naar achter strekken.
* Tegenstander valt over je, ondertussen gooi je hem door met je hoofd tussen zijn benen te duwen
en hem over te kieperen.
Go-ten - 5:
* Ze pakken je 2 handen weer vast.
* Je stapt in en doet shio-nage, door recht te komen en in te stappen.
* Neerleggen en controleren, zoals bij osae waza.
Stage info algemeen:
* Nooit ver uitstappen.
* Steeds naar tegenstander kijken, maar ook de houding en voeten zijn dan meestal naar de tegenstander gericht. Dat helpt bij de technieken.
* Arm opheffen = gaat beter met handpalm naar boven gericht.
Stage info ushiro kata otoshi:
* op omote: arm laten komen en laten passeren
Stage info ura ude nage:
* Niet over het gezicht.
* Tai sabaki = oo-irimi, niet volledig. Je stopt als je voeten parallel staan. Dus linkervoet niet achter de rechter!
* Dan kan je gemakkelijker inkomen.
* Ook niet te ver wegdraaien.
* De techniek in je centrum, de arm omdraaien naar je rechtervoet toe. Je smijt hem dus voor je.

== Katori
=== Iai jutsu

1. Kusangai no kata
Met knie wegtrekken.

2. Nuki uchi no kanta
Sprong en steek.

3. U ken
Naar links kijken, slag, terugkomen, steken en genadeslag.

4. Sa ken
Naar rechts kijken, slag, langs onder naar links, naar voren, steken en genadeslag.

5. 
Power jump.
(niet zeker van volgorde 3, 4 en 5)

=== Suwari waza no kata

Het zijn oefeningen, geen technieken.
1. Aanvaller: Tegenstander zit passief, handen op zijn dijbenen. Tenen actief zetten, met rechterhand zijn rechterhand vastpakken, maar met je gewicht naar voor, zodat je zijn hand ook tegenhoud. Uitvoerder: in een cirkel, naar zijn linker achterkant gaan, dan naar buiten terugkomen. Hij valt, ineens meedraaien. Zijn arm vastpakken en tegen je rechterdijbeen klemmen. Nen tooo doen, met ura ken. Arm scheppen met linkerhand en tussen je linkerkant en zijn lichaam leggen. Schuin in chico zitten. En terug naar je plaats met passieve tenen. Aanvaller: Rechterknie moet omhoog zijn bij het liggen, linkerbeen gestrekt. Bij de tooo, gezicht beschermen. Wegdraaien over je linkerbeen, maar je linkerknie mag de grond niet raken (voos regelke, slaagt op ni veel, uitvinding van meester Floquet). Dan terug naar je plaats gaan in chico.
2. Idem, maar met 2 handen tegelijk vastpakken. Uitvoerder: idem doen, maar je linkerarm werkt nu ook mee, in een cirkelbeweging naar de oksel van de tegenstander.
3. Slag met de zijkant van de vuist, naar het gezicht. Gelijk eskrima aanval 1 met mes. Uitvoerder: Met linker snijkant hand, in zijn schouder stoempen en hem zo in een cirkelbeweging uit evenwicht brengen. Opgelet: je tegenaanval moet vertrekken van zodra de aanvaller nog maar denkt aan vertrekken.
4. Wurging. Tenen actief. Pause. Aanvallen, door met beide handen naar de nek te grijpen. Uitvoerder: ineens naar voor vallen met je schouders. Tegenstander naar de grond brengen, door je ene schouder te laten zakken en je andere te laten mee sturen. Cfr. oefening 2.

=== General

Oude scholen (Katori, daito ryuu): rechterkant naar kamiza (kant embleem) = leerling, andere kant = leraar.
Aikibudo: linkerkant naar kamiza (kant embleem) = leerling, andere kant = leraar.
