== Aikibudo
Mae kumi tsuki: inkomen om iemand omver te leggen, met 1 van de schouders eerst.
Daar moet een neji kote kaeshi op gedaan worden (met oo-irimi), maar eerst een hiki met de 2 handen gekruist opvangen en gedurende heel de beweging de pols van de tegenstander begeleiden.
Stage info ryote ippo dori:
* niet uit evenwicht brengen door arm te strekken naar voren! Bekken draaien en dan plaats maken en direct uitstappen. Anders lost hij en gaat hij naar een wurging.
Stage info mukae daoshi:
* Opletten met de arm die je onder controle neemt: die breng je naar beneden, maar die moet langs de buitenkant blijven. Anders zal je het wel voelen aan je ballen.
* Zie ook dat zijn schouder niet te veel gedraaid is, zodat zijn rug in een rechte kamae houding komt. Dat zorgt voor de problemen met het wringen aan de nek en dat je arm-kracht moet gebruiken.
Go-ten - 1:
* Op knieën zitten, ze pakken je rechterhand vast met hun rechterhand. Klem zetten (vingers achteruit plooien), naar boven. Arm over je hoofd brengen.
* Klem zetten hierboven, door eerst je een beetje te richten naar tegenstander (knieën iets draaien/bijschuiven naar rechts).
* Onderwegen arm breken op je hoofd.
* Arm verder schuiven en in je nek leggen, zodat een elleboog klem in de richting van je gi-lijn gezet wordt.
Go-ten - 2:
* Ze pakken je linkerarm vast, in het voorbij-gaan. Vastpakken gebeurd met de rechterarm.
* Draaien en de arm over je hoofd plaatsen, zodat hij aan de ander kan komt.
* Je bent helemaal meegedraaid, je knieën zijn nu naar rechts gericht. Dus 270 graden gedraaid.
* Omver leggen, met je rechterschouder.
Go-ten - 3:
* Ze wurgen je langs achter.
* Arm vastpakken en tegenstander naar voren smijten, met je gewicht.
* Linkervoet gaat naar buiten.
Go-ten - 4:
* Ze pakken je 2 polsen langs voor vast, met hun 2 handen.
* Kracht breken (cfr. Aiki)
* je armen naar achter strekken.
* Tegenstander valt over je, ondertussen gooi je hem door met je hoofd tussen zijn benen te duwen
en hem over te kieperen.
Go-ten - 5:
* Ze pakken je 2 handen weer vast.
* Je stapt in en doet shio-nage, door recht te komen en in te stappen.
* Neerleggen en controleren, zoals bij osae waza.
Stage info algemeen:
* Nooit ver uitstappen.
* Steeds naar tegenstander kijken, maar ook de houding en voeten zijn dan meestal naar de tegenstander gericht. Dat helpt bij de technieken.
* Arm opheffen = gaat beter met handpalm naar boven gericht.
Stage info ushiro kata otoshi:
* op omote: arm laten komen en laten passeren
Stage info ura ude nage:
* Niet over het gezicht.
* Tai sabaki = oo-irimi, niet volledig. Je stopt als je voeten parallel staan. Dus linkervoet niet achter de rechter!
* Dan kan je gemakkelijker inkomen.
* Ook niet te ver wegdraaien.
* De techniek in je centrum, de arm omdraaien naar je rechtervoet toe. Je smijt hem dus voor je.

== Katori
=== Iai jutsu

1. Kusangai no kata
Met knie wegtrekken.

2. Nuki uchi no kanta
Sprong en steek.

3. U ken
Naar links kijken, slag, terugkomen, steken en genadeslag.

4. Sa ken
Naar rechts kijken, slag, langs onder naar links, naar voren, steken en genadeslag.

5. 
Power jump.
(niet zeker van volgorde 3, 4 en 5)

=== Suwari waza no kata

Het zijn oefeningen, geen technieken.
Afstand van 4 halve matten.
Groeten naar de sensei.
Naar mekaar draaien.
Groeten.
Zitten.
In shiko naar mekaar gaan.
Tegenover mekaar zitten, 2 vuisten tussen laten.
1. Aanvaller: Tegenstander zit passief, handen op zijn dijbenen. Tenen actief zetten, met rechterhand zijn rechterhand vastpakken, maar met je gewicht naar voor, zodat je zijn hand ook tegenhoud. Uitvoerder: in een cirkel, naar zijn linker achterkant gaan, dan naar buiten terugkomen. Hij valt, ineens meedraaien. Zijn arm vastpakken en tegen je rechterdijbeen klemmen. Nen tooo doen, met ura ken. Arm scheppen met linkerhand en tussen je linkerkant en zijn lichaam leggen. Schuin in chico zitten. En terug naar je plaats met passieve tenen. Aanvaller: Rechterknie moet omhoog zijn bij het liggen, linkerbeen gestrekt. Bij de tooo, gezicht beschermen. Wegdraaien over je linkerbeen, maar je linkerknie mag de grond niet raken (voos regelke, slaagt op ni veel, uitvinding van meester Floquet). Dan komt ge wel schoon terug recht. Dan terug naar je plaats gaan in chico.
2. Idem, maar met 2 handen tegelijk vastpakken. Uitvoerder: idem doen, maar je linkerarm werkt nu ook mee, in een cirkelbeweging naar de oksel van de tegenstander.
3. Slag met de zijkant van de vuist, naar het gezicht. Gelijk eskrima aanval 1 met mes. Uitvoerder: Met linker snijkant hand, in zijn schouder stoempen en hem zo in een cirkelbeweging uit evenwicht brengen. Opgelet: je tegenaanval moet vertrekken van zodra de aanvaller nog maar denkt aan vertrekken.
4. Wurging. Tenen actief. Pause. Aanvallen, door met beide handen naar de nek te grijpen. Uitvoerder: ineens naar voor vallen met je schouders. Tegenstander naar de grond brengen, door je ene schouder te laten zakken en je andere te laten mee sturen. Cfr. oefening 2.
Bij de laatste, blijft de uitvoerder zitten, totdat de aanvaller rechtkomt. Als aanvaller, moet je met gestrekt rechterbeen blijven liggen. Linkerknie omhoog. En dan rechtkomen. Dat is zo goed als onmogelijk, dus zet even je rechterhand bij. Linkerbeen komt dan onder je en je eindigt dan in chico.
Beiden gaan in chico naar hun plaats, die van in't begin met 4 halve matten tussen. Rechtstaan, draaien naar de sensei. Draaien naar mekaar. Groeten.

=== General

Oude scholen (Katori, daito ryuu): rechterkant naar kamiza (kant embleem) = leerling, andere kant = leraar.
Aikibudo: linkerkant naar kamiza (kant embleem) = leerling, andere kant = leraar.

== Katori

=== Naginata algemeen

Je houdt de bokken vast met je linkerhand, onderaan bij de kashira. Die hand blijf je vasthouden, en daar beweeg je de bokken mee. Die beweegt voor de rest niet en blijft in die positie.
Als je de bokken als meetstok gebruikt, door de punt te aligneren met de punt van de naginata, dan komt die vuist ter hoogte van de plaats waar je de naginata met de rechtervuist vastpakt. Die vuist blijft daar ook, die mag niet van positie veranderen. Tenzij je van kant wisselt, natuurlijk. Maar niet tijdens de bewegingen van de technieken.

Bo: linkerhand bovenaan en naar beneden drukken.
Naginata: linkerhand onderaan, ter ondersteuning.

=== Naginata 1ste

A: Leerling (naginata)
B: Leraar (bokken)

A: In linkerhand leggen, met scherpe kant naar boven gezicht, maar punt naar beneden onder 45 graden.
   Groeten, zonder dat de naginata beweegt.

A: Linkervoet naar voor.
   Rechtervoet.
   Timing: links - rechts 1001 1002

   Tegelijkertijd: naginata vastpakken langs links, terwijl je de scherpe kant naar beneden draait en de punt omhoog brengt. Ook hier richten naar de keel.

A: Leraar achteruit dreigen met 2 passen.

B: 2 passen achteruit gaan, dreigende seigan no kamae aanhouden.

A: Achteruit. Naginata recht zetten, langs de rechterkant, en in een soort van ino-kamae staan.

   Linkervuist houdt de naginata vast op de correcte positie. Dat gaan we nu wisselen, door de rechtervuist naar boven te schuiven. Als je aan de linkervuist komt, gaat die ter plaatse open, zodat de rechtervuist erin kan schuiven en de positie kan overnemen. Dan schuift de linkervuist verder naar beneden, omsluit de naginata weer op een lagere positie.

  Linkervoet naar voor in dreigende kamae.

  Rechtervuist omhoog brengen, tot op je voorhoofd. Linkervuist gaat naar beneden, zodat de positie van de naginata wijzigt naar hetvolgende:
  - Scherpe kant naar boven gericht,
  - Voorste punt naar beneden gericht, hoek van 45 graden

B: Sha no kamae.
   Bokken terug naar joodan no kamae brengen.
   Tegelijkertijd voeten samen.
   Maki uchi.
   Links - rechts inkomen + 2de maki uchi, als aanval naar het hoofd.

A: Achteruit hiki. Belangrijk is dat je recht achteruit gaat, in dezelfde lijn. Tegelijk de kromming van het zwaard-gedeelte lepelend naar rechts op de bokken leggen, ter blokkering.

   Kubi. Dit is naar voor schieten, links-rechts en naar de keel aanvallen.

B: Uitstappen naar rechts en ko-gasumi doen.

A: Do aanvallen vanuit die hoge positie. Eerst do van "Do - do - retirer".

B: De beweging van de naginata volgen en je rechterbeen achteruit smijten. Zo kan de naginata paseren.

A: Achteruit in ino.
   Nogmaals do aanvallen met kubi enz.

B: Uitstappen naar de andere kant. Proberen do aan te vallen.

A: Shiiit! Achteruit stappen, voeten samen en de naginata dichtbij trekken.
   Punt naginata is rechts onder met de scherpe kant naar boven, naginata voor je lichaam onder een hoek van 45 graden.

B: Naar joodan.

A: Rechtervoet naar de linker zetten in soort van chidori.
   Zo lang mogelijk naar de tegenstander kijken en dan snel ronddraaien.
   Buik horizontaal openrijten.

B: Pareren door do de aanval te blokkeren.

A: Naar ino kamae.

B: Naar joodan.

A: Do aanvallen, same thing.

B: Pareren zoals voordien, maar bij de laatste beweging ineens inkomen en men naar de kop aanvallen.

A: Linkervoet naar links uitstappen.
   Rechtervoet bijtrekken en tegelijkertijd: met onderste deel naginata een draaibeweging maken om te pareren.
   Eindigen in een soort van ino kamae.

A: Do aanvallen enz.

B: Idem pareren als bij de vorige do.

A: Idem pareren met onderste deel naginata en weer eindigen in een soort van ino kamae.

B: Naar ino kamae gaan.
   Finale slag zetten naar de nek.

A: Uitstappen naar links en de pols opensnijden langs onder.
   Naginata naar achter brengen om op te spannen. Armen moeten volledig naar achter gestrekt zijn.
   Dan naar voor schieten en "doooo".
   Naginata moet in een kamae in je centrum zijn, naginata niet te ver voor u strekken. Natuurlijke comfortabele positie aanhouden.

==== 
